# Generated by Django 5.0.5 on 2024-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
