# Generated by Django 5.0.5 on 2024-05-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_alter_ad_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
